# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('shirt_id', models.IntegerField(primary_key=True, serialize=False)),
                ('selling_price', models.IntegerField()),
                ('shirt_name', models.CharField(max_length=100)),
                ('shirt_brand', models.CharField(max_length=100)),
                ('shirt_color', models.CharField(max_length=10)),
                ('shirt_type', models.CharField(max_length=20)),
                ('shirt_material', models.CharField(max_length=20)),
                ('shirt_size', models.CharField(choices=[('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('S', 'S')], default='M', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='T_shirt',
            fields=[
                ('t_shirt_id', models.IntegerField(primary_key=True, serialize=False)),
                ('selling_price', models.IntegerField()),
                ('t_shirt_name', models.CharField(max_length=100)),
                ('t_shirt_brand', models.CharField(max_length=100)),
                ('t_shirt_color', models.CharField(max_length=10)),
                ('t_shirt_type', models.CharField(max_length=20)),
                ('t_shirt_material', models.CharField(max_length=20)),
                ('t_shirt_size', models.CharField(choices=[('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('S', 'S')], default='M', max_length=2)),
            ],
        ),
    ]
