# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=150)),
            ],
        ),
        migrations.RenameField(
            model_name='shirt',
            old_name='shirt_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='shirt',
            old_name='shirt_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='shirt',
            old_name='shirt_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='shirt',
            old_name='shirt_material',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='shirt',
            old_name='selling_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='shirt',
            old_name='shirt_size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='shirt',
            old_name='shirt_name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='shirt',
            old_name='shirt_type',
            new_name='type',
        ),
    ]
